/**
 * [description]
 */
export enum ErrorTypeEnum {
  /**
   * AUTH
   */
  AUTH_INCORRECT_CREDENTIALS = 'AUTH_INCORRECT_CREDENTIALS',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',

  NEW_PASSWORD_AND_OLD_PASSWORD_CANNOT_BE_SAME = 'NEW_PASSWORD_AND_OLD_PASSWORD_CANNOT_BE_SAME',
  AUTH_INCORRECT_CONFIRMATION_EMAIL_CODE = 'AUTH_INCORRECT_CONFIRMATION_EMAIL_CODE',
  AUTH_PASSWORDS_DO_NOT_MATCH = 'AUTH_PASSWORDS_DO_NOT_MATCH',

  /**
   * USER
   */
  USER_ALREADY_EXIST = 'USER_ALREADY_EXISTS',
  USERS_NOT_FOUND = 'USERS_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  /**
   * ACCOUNT
   */
  ACCOUNT_ALREADY_EXIST = 'ACCOUNT_ALREADY_EXISTS',
  ACCOUNTS_NOT_FOUND = 'ACCOUNTS_NOT_FOUND',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',

  /**
   * CATEGORY
   */
  CATEGORY_ALREADY_EXIST = 'CATEGORY_ALREADY_EXISTS',
  CATEGORIES_NOT_FOUND = 'CATEGORIES_NOT_FOUND',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',

  /**
   * TRANSACTION
   */
  TRANSACTION_ALREADY_EXIST = 'TRANSACTION_ALREADY_EXISTS',
  TRANSACTIONS_NOT_FOUND = 'TRANSACTIONS_NOT_FOUND',
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',

  /**
   * EXCHANGERATE
   */
  EXCHANGERATE_NOT_FOUND_FROM_CACHE = 'EXCHANGERATE_NOT_FOUND_FROM_CACHE',
  EXCHANGERATE_NOT_FOUND_FROM_API = 'EXCHANGERATE_NOT_FOUND_FROM_API',
}
